### ISSUE TITLE
What version of WinDivert is this compatible with?

### ISSUE THREAD

**Issue by alandao** [TechnikEmpire/DivertPInvoke#1]
There's two versions of WinDivert,1.1.8 or 1.2.0rc. Which one does this wrapper work with?

**Comment by TechnikEmpire** [comment]
@alandao 1.2 but AFAIK there is no breaking API difference between the two versions. The same major version number indicates this as well.

**Comment by MrRandom92** [comment]
@TechnikEmpire Is this compatible with 32-bit? I receive "incorrect format (Exception from RESULT:0x8007000B.)" or is there something I need to change in the class?

**Comment by TechnikEmpire** [comment]
@TodM there's a dll and a sys file for both 32 and 64 bit versions of WinDivert. If you're compiling 32 bit to run on a 64 bit system then you need to link to the 32 bit dll but include the 64 bit sys file. You can't run a 32 bit driver in a 64 bit host.

**Comment by MrRandom92** [comment]
@TechnikEmpire Thanks that did the trick. Off topic, but I got the latency queue working the only trouble now is the queues overflow even when I try to keep them at 800 packets max, and I am not sure where to find help with the issue as you and Basil know best on this subject is there anywhere I can show you the latest source?

**Comment by TechnikEmpire** [comment]
@TodM I'm not sure. Stackoverflow is a junk yard managed by junk programmers so I can't say. As far as myself I can't really help I have too much to do.
